### ISSUE TITLE
Missing armv7s architecture 

### ISSUE THREAD

**Issue by MattFoley** [Kochava/kochava-tracker-ios-sdk-cocoapod#6]
Previous versions of Kochava offered armv7s architecture in the compiled library. Is there a way to get a version of 3.3.0 with armv7s built in?

**Comment by johnbushnell** [comment]
armv7s was deprecated some time ago, in Xcode 6.  It was no longer built into the compiled SDK beginning with 3.1.5 in June 2017.  The last version which had it was 3.1.4, released April 11th 2017.  We weren't aware of any continued use case for it.  What is the reason why you need it?

**Comment by johnbushnell** [comment]
I guess the question I'm asking is, to our knowledge there is no case where Apple requires it.  Why are you building for it?

**Comment by MattFoley** [comment]
Typically, just for our users which require it. I think we can drop it, because you're right, it only offers a small marginal performance increase over armv7 on a small number of devices.

**Comment by johnbushnell** [comment]
👍
