### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by coffeemao** [Kochava/kochava-tracker-ios-sdk-cocoapod#9]
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x000000019b41983c in xpc_get_type ()
#1	0x000000019b425a60 in xpc_connection_get_pid ()
#2	0x000000018c29bc44 in WebKit::WebProcessProxy::didFinishLaunching(WebKit::ProcessLauncher*, IPC::Connection::Identifier) ()
#3	0x000000018c15afd8 in WebKit::ProcessLauncher::didFinishLaunchingProcess(int, IPC::Connection::Identifier) ()
#4	0x000000018c15d978 in _ZNSt3__110__function6__funcIZZN6WebKitL16connectToServiceERKNS2_15ProcessLauncher13LaunchOptionsEbPS3_MS3_FviN3IPC10Connection10IdentifierEEPNS2_12_GLOBAL__N_110UUIDHolderEEUb_E3$_0NS_9allocatorISG_EEFvvEEclEv ()
#5	0x0000000187a63150 in WTF::RunLoop::performWork() ()
#6	0x0000000187a637ac in WTF::RunLoop::performWork(void*) ()
#7	0x0000000185e8c5a4 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#8	0x0000000185e8c038 in __CFRunLoopDoSources0 ()
#9	0x0000000185e89d38 in __CFRunLoopRun ()
#10	0x0000000185db8dc0 in CFRunLoopRunSpecific ()
#11	0x0000000190f0c088 in GSEventRunModal ()
#12	0x000000018b492f44 in UIApplicationMain ()
#13	0x000000010033434c in main at /Users/ember/Desktop/Rongle/wangle_src/WonderVoice/Trunk/MoboNews/MoboNews/main.m:14
#14	0x000000019b2068b8 in start ()

**Comment by coffeemao** [comment]
iphone 5s,9.0.2 crash

**Comment by coffeemao** [comment]
KochavaTrackeriOS Version is 3.5.0 iOS  SDK

**Comment by coffeemao** [comment]
(lldb) bt
Voice was compiled with optimization - stepping may behave oddly; variables may not be available.
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000019b41983c libxpc.dylib`xpc_get_type
    frame #1: 0x000000019b425a60 libxpc.dylib`xpc_connection_get_pid + 20
    frame #2: 0x000000018c29bc44 WebKit`WebKit::WebProcessProxy::didFinishLaunching(WebKit::ProcessLauncher*, IPC::Connection::Identifier) + 268
    frame #3: 0x000000018c15afd8 WebKit`WebKit::ProcessLauncher::didFinishLaunchingProcess(int, IPC::Connection::Identifier) + 100
    frame #4: 0x000000018c15d978 WebKit`_ZNSt3__110__function6__funcIZZN6WebKitL16connectToServiceERKNS2_15ProcessLauncher13LaunchOptionsEbPS3_MS3_FviN3IPC10Connection10IdentifierEEPNS2_12_GLOBAL__N_110UUIDHolderEEUb_E3$_0NS_9allocatorISG_EEFvvEEclEv + 60
    frame #5: 0x0000000187a63150 JavaScriptCore`WTF::RunLoop::performWork() + 484
    frame #6: 0x0000000187a637ac JavaScriptCore`WTF::RunLoop::performWork(void*) + 36
    frame #7: 0x0000000185e8c5a4 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
    frame #8: 0x0000000185e8c038 CoreFoundation`__CFRunLoopDoSources0 + 540
    frame #9: 0x0000000185e89d38 CoreFoundation`__CFRunLoopRun + 724
    frame #10: 0x0000000185db8dc0 CoreFoundation`CFRunLoopRunSpecific + 384
    frame #11: 0x0000000190f0c088 GraphicsServices`GSEventRunModal + 180
    frame #12: 0x000000018b492f44 UIKit`UIApplicationMain + 204
  * frame #13: 0x00000001002f037c Voice`main(argc=<unavailable>, argv=<unavailable>) at main.m:14 [opt]
    frame #14: 0x000000019b2068b8 libdyld.dylib`start + 4
(lldb)

**Comment by johnbushnell** [comment]
I'm not seeing anything in your crash that relates to the Kochava SDK, i.e. none of our symbols.  Is there something specific you want to call out?
